### ISSUE TITLE
Configure XML#builder() to use setValidating or setSchema or none

### ISSUE THREAD

**Issue by avianey** [jenetics/jpx#116]
For now it calls `factory.setValidating(true);` which is inappropriate in some use case :

- offline / schema URL not reachable
- Android ecosystem where validation throw error

Would be great to be able to configure the behaviour for `factory.newDocumentBuilder()`

**Comment by avianey** [comment]
since there's only two usage for DocumentBuilderFactory.newInstance() we could :

- use a kind of DocumentBuilderFactoryInstanceProvider
- or use DocumentBuilderFactory#newInstance(String factoryClassName, ClassLoader classLoader)

Any preference for a pull request ? (later one is only supported since 1.6)

**Comment by jenetics** [comment]
Since there are several places where I have to created XML related classes, the more general solution of a SPI would be desirable. 

```java
package io.jenetics.jpx;

import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.stream.XMLInputFactory;
import javax.xml.stream.XMLOutputFactory;

public abstract class XMLProvider {
    protected XMLProvider() {
    }
    // Used for reading files.
    public XMLInputFactory xmlInputFactory() {
        return XMLInputFactory.newInstance();
    }
    // Used for writing files.
    public XMLOutputFactory xmlOutputFactory() {
        return XMLOutputFactory.newInstance();
    }
    // Used for creating GPX extensions documents.
    public DocumentBuilderFactory documentBuilderFactory() {
        final DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        factory.setValidating(true);
        factory.setIgnoringElementContentWhitespace(true);
        factory.setNamespaceAware(true);
        return factory;
    }
    public static XMLProvider provider() {
        // Do service lookup and return default impl if nothing is found.
        return null;
    }
}
```
I think this could solve the XML _problems_ once and for all ;-)

**Comment by jenetics** [comment]
Merged into r1.7.0 branch.
