### ISSUE TITLE
Extension parse error

### ISSUE THREAD

**Issue by derekPrivate** [jenetics/jpx#121]
I get an error when parsing the attached GPX file, containing an extension (this is cut down example, showing the problem)

ERROR:  'ParseError at [row,col]:[14,34]
Message: http://www.w3.org/TR/1999/REC-xml-names-19990114#ElementPrefixUnbound?gpxtpx&gpxtpx:TrackPointExtension'
Error: Invalid 'gpx' input. (/Users/derekmorris/Downloads/test.gpx)

[test.gpx.zip](https://github.com/jenetics/jpx/files/4186955/test.gpx.zip)

**Comment by derekPrivate** [comment]
This was originally found with v1.6.0 but I just upgraded to 1.7.0 and get the same error.

**Comment by derekPrivate** [comment]
Sorry, a bit more digging shows that I need to add this to the schema:
xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v2"

but... I am downloading this file (and many others like it) from strava.com. Is there a way add this schema programmatically, rather than directly in the GPX file?

**Comment by jenetics** [comment]
I don't see an easy way to do this programmatically. You might want have a look at the `XMLProvider` class and try to implement an alternative version.

**Comment by derekPrivate** [comment]
OK, I decided to 'fix' this by inserting the schema into the GPX stream before it was read by the parser. Not ideal, but it does work. Thanks for the help
