### ISSUE TITLE
Builder.creator(string) isn't doing anything

### ISSUE THREAD

**Issue by benlc** [jenetics/jpx#122]
It appears that `Builder.creator` isn't working and the GPX header remains the same. Tested on 1.4 and 1.7

`<?xml version='1.0' encoding='UTF-8'?><gpx version="1.1" creator="JPX - https://github.com/jenetics/jpx" xmlns="http://www.topografix.com/GPX/1/1">`

**Comment by jenetics** [comment]
I can't reproduce the error.
```java
GPX.writer("    ").write(
    GPX.builder().creator("ADSDF").build(),
    System.out
);
```
Will print
```
<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="ADSDF" xmlns="http://www.topografix.com/GPX/1/1"></gpx>
```
