### ISSUE TITLE
Problem with the terminal command

### ISSUE THREAD

**Issue by louisJ20** [jenetics/jpx#130]
Hello,

I encounter a problem with the bash command. When I execute your command, the message is showed : "./gradle: is a directory"

Could you help me ?

Thanks in advance

**Comment by jenetics** [comment]
This is a  bug in the README. The command should be `./gradlew`.

**Comment by louisJ20** [comment]
> ./gradlew

I tried "./gradlew test" but an error is showed

**Comment by jenetics** [comment]
"... an error is showed" is a little bit to generic ;-) A console output or a stacktrace  would be helpful. Which library version are you using? Which Java version are you using? Which OS are you using?

**Comment by louisJ20** [comment]
> "... an error is showed" is a little bit to generic ;-) A console output or a stacktrace  would be helpful. Which library version are you using? Which Java version are you using? Which OS are you using?

Sorry, i use the 8th version of Java and my OS is MacOS. The error is : "build failed"

**Comment by louisJ20** [comment]
> > "... an error is showed" is a little bit to generic ;-) A console output or a stacktrace  would be helpful. Which library version are you using? Which Java version are you using? Which OS are you using?
> 
> Sorry, i use the 8th version of Java and my OS is MacOS. The error is : "build failed"

It's ok. The jar file is generated. Now, when I code, I cannot recover the speed the GPW file ? Could you help me ?

Thanks in advance

**Comment by jenetics** [comment]
I would really try to help you. But again, you gave me no information for doing so. It might be clear for you, what  you are trying to do and which results you are expecting. But I don't. Ask yourself: what information, or artifacts (GPX files), do I need for reproducing the problem locally on my machine? What is the expected outcome? What is the actual outcome? If you get an exception, a stacktrace is very valuable.

Additionally it seems to be a different problem as described in this ticket. So, if you create a new ticket with the needed information/artifacts, which allows me to reproduce the problem, I will have a look.

Regards
Franz

**Comment by louisJ20** [comment]
It's ok, I created a new ticket. Thank you very much for your help.
