### ISSUE TITLE
code example of how to write and retrieve from database

### ISSUE THREAD

**Issue by gbo999** [jenetics/jpx#133]
can you write a code example of how to write/retrieve from database.

thanks

**Comment by jenetics** [comment]
Hi @gbo999 

Reading and writing GPX-data from/to a DB can be an tedious task. First of all you have to decide what you want to store in the DB. Do you want only store a list of `WayPoint`s, the DB model will contain of one table with the columns you want to store. In the following branch I tried to create a _full_ DB model for GPX data: https://github.com/jenetics/jpx/tree/issues/JPX-1-JDBC_access
As you can see, this requires quite a lot of code. To simplify it, you have to think about a simplification of the requirements.

**Possible requirements**
* Do you need to store the whole GPX structure in the DB? Maybe it is sufficient to only store a list of way-points. Or is it possible to store the data as it is (as XML) as TEXT in the DB. You might then be using the XML search capability of the DB, if available.
* Do you need to perform _spacial_ search for way-points?
* Which GPX data should be searchable?

There lies a lot of complexity in your request. This is the main reason, why I haven't completed ticket #1 yet. Maybe you can elaborate your use-case you have in mind in a greater detail.

Regards
Franz

**Comment by gbo999** [comment]
i am not sure what type of file i need, but i want store and retrieve tracks/routs

**Comment by jenetics** [comment]
In this case, you should definitly have a look at the mentioned branch. Especially at the DB model (https://github.com/jenetics/jpx/blob/issues/JPX-1-JDBC_access/jpx.jdbc/src/main/resources/model-mysql.sql), which is _complete_ and contains all information of a `GPX` object/file. The rest are _normal_ SQL selects/inserts. 

As you already noticed, this is no _ready to use_ example and there is quite some coding work to do to make it work. But it should give you some guadance where to start and how this can be implemented.
