### ISSUE TITLE
The attached gpx file doesn't get parsed even when its valid.

### ISSUE THREAD

**Issue by ShreyasTandale** [jenetics/jpx#143]
It complains about the version attribute. Can there be any workaround to this?
[new.gpx.zip](https://github.com/jenetics/jpx/files/6116513/new.gpx.zip)

**Comment by jenetics** [comment]
Hi @ShreyasTandale, your attached GPX file is unfortunately not valid.
```xml
<gpx>
    <trk>
        ...
    </trk>
</gpx>
```
It misses the `version` and `creator` attribute.
```xml
<gpx version="1.1" creator="creator_XYZ" xmlns="http://www.topografix.com/GPX/1/1">
    <trk>
        ...
    </trk>
</gpx>
```
Due to the GPX [specification](https://www.topografix.com/GPX/1/1/), this attributes are not optional. You can fix your GPX file by adding these attributes to your file.

**Comment by ShreyasTandale** [comment]
Thanks @jenetics for the prompt response. I tried the workaround you suggested and the files do get parsed now. Closing this issue.
