### ISSUE TITLE
New line issues in tests

### ISSUE THREAD

**Issue by ngx472** [jenetics/jpx#167]
Hi

Just installed on Windows and  several test failed.
e.g. issue162_NumberFormattingParsing
The issue is that the following string has CRLF as line ends 
final var string = GPX.Writer.DEFAULT.toString(gpx); 
Whereas the expected value happens to have LF only (depends on the IDE setup and whether the file was touched and saved)
The solution would be to compare while ignoring line endings.
I believe it should be a feature of junit but team disagrees https://github.com/junit-team/junit5/issues/2394

Thanks
Ngx

**Comment by jenetics** [comment]
This can be fixed by using [AssertJ](https://assertj.github.io/doc/) and use
```java
org.assertj.core.api.Assertions
    .assertThat("asdf")
    .isEqualToIgnoringNewLines("sdf");
```
instead the native TestNG assertion.

**Comment by jenetics** [comment]
Merged into r3.1.0.
