### ISSUE TITLE
Gradle build fails with missing module jakarta.jakartaee.web.api

### ISSUE THREAD

**Issue by chh345** [jenetics/jpx#180]
Hello

./gradlew build fails for me with "error: module not found: jakarta.jakartaee.web.api requires jakarta.jakartaee.web.api;" (module-info.java:163). With maven I would just add it as a dependency. However the build.gradle.kts/settings.gradle.kts are too complex for me to add it manually. Could you help me adding it there?

Thanks for your work and best regards

**Comment by jenetics** [comment]
Hi!

Do you want to try to build the JPX library itself or an application, which uses the library? Building the JPX library works on GitHub and on my local machine. If it doesn't compile on yours, I need some additional information, like the version of the JDK, the JPX version you are trying to build and the OS.

lg

**Comment by chh345** [comment]
Thanks for your answer. I wanted to build the library itself and local changes were responsible for the error.

Solution for me was, overwriting those changes and build again:
`git fetch --all`
`git reset --hard origin/master`
