### ISSUE TITLE
Improve error handling for invalid gpx files

### ISSUE THREAD

**Issue by NopMap** [jenetics/jpx#182]
Once in a while, people try to load an invalid gpx file with my tool which uses JPX. Unfortunately, JPX just throws an InvalidObjectException("Invalid 'gpx' input.") and completely hides the reason of the exception. So you have no means to find and correct the fault.
E.g. today I am trying to fix an unloadable file and I needed to go deep into the ElementReader with a Debugger to find out that the reason is an invalid element "metadate".

Actually the parser originally throws an exception that contains exactly the relevant information in a XMLStreamException with the message `"Unexpected element <metadate>"`. But unfortunately this is caught in GPX.Reader.read() and a nondescript InvalidObjectException is thrown instead.

**Suggestion**: Append the message from the XMLStreamException to the InvalidObjectException or output the message to the console directly before throwing the InvalidObjectException. In both cases, the faulty element would be visible on the console, enabling the user to fix the gpx.

**Comment by jenetics** [comment]
I had a look at the code and can't exactly locate the place, where the error information is stripped. The place where the `XMLStreamException` is converted into a `InvalidObjectException`, the error messages from the original exception is added to the new exception.

Can you attach an example GPX file, which triggers this kind of error? Where you would do the suggested fix? Not exactly sure, which place you have in mind.

**Comment by NopMap** [comment]
My bad, this has already been improved. I should have checked the latest version before creating an issue.
