### ISSUE TITLE
Add `Length.Unit.Foot` and `Length.Unit.NauticalMile`

### ISSUE THREAD

**Issue by sirthias** [jenetics/jpx#35]
Both are popular units for altitudes and distances, respectively.
It's be great if they'd have first-class support.
(Maybe even more so than inch, yards and statute miles...)

**Comment by jenetics** [comment]
Merged into r1.2.0. branch.

**Comment by sirthias** [comment]
Awesome!
Thank you for being so responsive in getting this in!
