### ISSUE TITLE
bounds element

### ISSUE THREAD

**Issue by hallvard** [jenetics/jpx#49]
I tried reading the RT file in this zip http://users.telenet.be/meirenwi/Achterbroek%20naar%20De%20Maatjes%20-%2013%20km%20RT.zip, and I had to remove the bounds element to make it load. With this element I got a NPE. I believe the schema at http://www.topografix.com/GPX/1/0/gpx.xsd indicates the bounds element is legal.

**Comment by jenetics** [comment]
JPX can currently only read GPX version 1.1. In ticket #25 I want to extend it read GPX version 1.0 files as well. And you are right, the NPE is not a nice behavior.

**Comment by hallvard** [comment]
Ah, I misread the 1.1 spec, I now see that the **bounds** element must be inside the **metadata** element. But it would be nice to support both 1.1 and 1.0 versions.

BTW, I tried to comment out the bounds element, and that hung the parser, e.g.

**Comment by hallvard** [comment]
I think you need a case for comments in the read method (almost at the bottom) in XMLReader with xml.next(), or else it hangs on the comment.

**Comment by jenetics** [comment]
I fixed the  XML comment issue in #51

**Comment by jenetics** [comment]
JPX still can read GPX files for version 1.0, but it know can ignore XML comments and using the _lenient_ mode will ignore all unknown elements. You can read 1.0 GPX file with

```java
boolean lenient = true;
GPX.read("file.gpx", lenient);
```
but it will, of course, ignore the metadata.
