### ISSUE TITLE
io.jenetics.jpx.TrackSegment not included in version 1.2.3

### ISSUE THREAD

**Issue by dghelprat** [jenetics/jpx#56]
Creating a new Maven project using jpx 1.2.3, the class TrackSegment is not visible:
`io.jenetics.jpx.GPX gpx = io.jenetics.jpx.GPX.read("tracks.gpx").toBuilder().build();`

And any other pieces of code involving TrackSegment:
`GPX gpx = GPX.read(input);
io.jenetics.jpx.Track t = gpx.getTracks().get(0);
io.jenetics.jpx.TrackSegment s = t.getSegments().get(0);`

Those lines work with version 1.2.2 .

**Comment by jenetics** [comment]
The only part of the code I touched in v1.2.3 was the (internal) XML reader. Can you attach your GPX file? With a randomly created GPX object I couldn't reproduce the error.

**Comment by dghelprat** [comment]
This is the file that was acquired from Maven, at 244KB uncompressed.
[jpx-1.2.3.zip](https://github.com/jenetics/jpx/files/1744622/jpx-1.2.3.zip)

Weirdly enough, I tried re-downloading the file yesterday and earlier today, but no differences appeared between retries; after deleting and downloading once again right now, the issue seems to have fixed by itself (JAR file measures 126KB, like the one from version 1.2.2).

**Comment by jenetics** [comment]
Strange. The MD5 checksum of the `jpx-1.2.3.jar` file I uploaded to Maven is `3208a00b661d7eb9534041173c5b3bc0` and has a size of 128619 bytes.

So the error is not reproducible?

**Comment by dghelprat** [comment]
Seems so. Maybe I was unlucky before! And thanks for the quick answers ;)
