### ISSUE TITLE
Handle common gpx extensions

### ISSUE THREAD

**Issue by rieserCh** [jenetics/jpx#59]
It would be a great benefit if common gpx-extensions like:

http://www.garmin.com/xmlschemas/GpxExtensionsv3.xsd
http://www.garmin.com/xmlschemas/TrackPointExtensionv1.xsd

would be supported. Or at least to get the raw xml of unknown sub-tags.

Sample file attached:

[Richmond.zip](https://github.com/jenetics/jpx/files/1784361/Richmond.zip)

**Comment by jenetics** [comment]
Merged into r1.5.0 branch.
