### ISSUE TITLE
Convert gpx to string

### ISSUE THREAD

**Issue by giloutho** [jenetics/jpx#61]
Many thanks for this nice library. 

When the GPX object is created, I want it as a string. I read javadoc, but I was unable to use GPX.Writer with method toString. Can you put a snippet ?

Additional question : for writing the GPX object to a file, I use GPX.write. I have no line breaks in the file. What is the correct way ?

**Comment by jenetics** [comment]
You can do it this way:
```java
final GPX gpx = ...;
System.out.println(GPX.writer("    ").toString(gpx));
```

**Comment by giloutho** [comment]
Many thanks... It's perfect now
