### ISSUE TITLE
ZoneId has no effect when writing to the GPX file

### ISSUE THREAD

**Issue by jamesweb1** [jenetics/jpx#63]
I try to write the GPX file with the local time (Asia/Taipei), but it always write the UTC time to the file. Following is my code:

```java
GPX.Builder gpx_builder = GPX.builder();
gpx_builder.addTrack(track -> track
                        .addSegment(segment -> segment
                                .addPoint(p -> p.lat(latitude).lon(longitude).time(timestamp, ZoneId.of("Asia/Taipei")))));
final GPX gpx = gpx_builder.build();
GPX.write(gpx, out_file);
```

for example: 
with timestamp 1517553382053, I expect
`<time>2018-02-02T14:36:22.053+08:00</time>` in the GPX file
but it always show `<time>2018-02-02T06:36:22.053+08:00</time>` in the GPX file

Is this an issue?

**Comment by jenetics** [comment]
This behavior is intended. If you convert the UNIX timestamp `1517553382053`, you get `Friday, February 2, 2018 6:36:22.053 AM`. The additional ZoneID doesn't change the timestamp, it _just_ adds the given zone to the timestamp. If you want to convert the UNIX time to your time zone, you have to do this:

```java
long ts = 1517553382053L;

// This line does your desired conversion of the local date time.
LocalDateTime ldt = LocalDateTime.ofInstant(Instant.ofEpochMilli(ts), ZoneId.of("Asia/Taipei"));
// This line creates a Zoned Date Time from the local date time, by just adding the time zone
ZonedDateTime zdt = ZonedDateTime.of(ldt, ZoneId.of("Asia/Taipei"));

System.out.println(ldt);
System.out.println(zdt);
```

**Comment by jamesweb1** [comment]
I know it does not change the timestamp, but I need to see the local time in the GPX file instead of the UTC time only. How can I achieve this?

In the intuitive way, I think I tell the timezone when I add the Point to my track so that the gpx file will display the readable time with the local time instead of the UTC time.

**Comment by jenetics** [comment]
Have you tried the code snipped I posted? The `ZonedDateTime`, `zdt`, should represent the time you want.
