### ISSUE TITLE
The GPX reader doesn't handle comments correctly.

### ISSUE THREAD

**Issue by NopMap** [jenetics/jpx#77]
It seems that #51 was not fully fixed. The following file causes an exception in jpx 1.4:

&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
&lt;!-- Generated by Christian Pesch's RouteConverter. See http://www.routeconverter.com --&gt;

&lt;gpx xmlns=&quot;http://www.topografix.com/GPX/1/1&quot; version=&quot;1.1&quot; creator=&quot;RouteConverter 2.26-SNAPSHOT-59&quot;&gt;
    &lt;trk&gt;
        &lt;name&gt;09-OKT-18 15:12:08&lt;/name&gt;
        &lt;trkseg&gt;
            &lt;trkpt lat=&quot;48.7065017&quot; lon=&quot;11.3178901&quot;&gt;
                &lt;ele&gt;374.6&lt;/ele&gt;
                &lt;time&gt;2018-10-09T11:57:05.000Z&lt;/time&gt;
                &lt;name&gt;Position 1&lt;/name&gt;
            &lt;/trkpt&gt;
        &lt;/trkseg&gt;
    &lt;/trk&gt;
&lt;/gpx&gt;

javax.xml.stream.XMLStreamException: Event type START_ELEMENT specified did not match with current parser event COMMENT

The reason is the comment. After removing it the exception disappears.

Of course, such comments are valid syntax and should work.

**Comment by jenetics** [comment]
Thank you for the report. Will be fixed for the next release.

**Comment by jenetics** [comment]
Merged into r1.5.0.
