### ISSUE TITLE
Unexpected element <trkpt>. in Garmin eTrex10 file 

### ISSUE THREAD

**Issue by ryanthara** [jenetics/jpx#82]
For playing a little bit with gpx files in an OSM context, I used version 1.4.0 of jpx.

In my test driven context there are some test methods to read a couple of my own Garmin eTrex 10 and Oregon files. They are only stored on the handheld device with the export functions of the Garmin firmware. I chose a couple of files I recorded over the last years with different versions.

Until the update to jpx 1.5.0 every test was green.

Now I got the following Exception:

`java.io.IOException: javax.xml.stream.XMLStreamException: Unexpected element <trkpt>.
	at io.jenetics.jpx.GPX$Reader.read(GPX.java:1143)
	at io.jenetics.jpx.GPX$Reader.read(GPX.java:1160)
	at io.jenetics.jpx.GPX$Reader.read(GPX.java:1174)
	at io.jenetics.jpx.GPX$Reader.read(GPX.java:1187)
	at io.jenetics.jpx.GPX.read(GPX.java:2054)`

A snippet from the simple test case:

        Assertions.assertTrue(Files.exists(Paths.get("src/test/resources/Track_19-JUN-18 182748.gpx")));

        try {
            GPX.read("src/test/resources/Track_19-JUN-18 182748.gpx")
                    .tracks()
                    .flatMap(Track::segments)
                    .flatMap(TrackSegment::points)
                    .forEach(System.out::println);
        } catch (IOException e) {
            e.printStackTrace();
        }

Nothing special I think.

[Track_19-JUN-18 182748.gpx.zip](https://github.com/jenetics/jpx/files/3418887/Track_19-JUN-18.182748.gpx.zip)

**Comment by jenetics** [comment]
Fixed and released in v1.5.1.
