### ISSUE TITLE
No Issue - [Imporvement] Upload release jar to central repository

### ISSUE THREAD

**Issue by timguy** [jenetics/jpx#99]
Thanks for the lib but could you upload the library to some repo?
E.g.: https://mvnrepository.com/
Background: Would like to use it via gradle and maybe some other maven guys could also make better use of it instead of compiling the .jar themself.

**Comment by jenetics** [comment]
Hmm...
https://mvnrepository.com/artifact/io.jenetics/jpx

**Comment by timguy** [comment]
argh you are so right. Was just watching in chapter **Dependencies** in the readme instead of seeing the nice grey/green batch. In maven I just searched for gpx instead of jpx. Thanks   :+1:

**Comment by jenetics** [comment]
Never mind :smiley:
